version: "3.9"

services:
  mysql-server:
   image: mysql:8.0.28
   command: 
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_bin
    --default-authentication-plugin=mysql_native_password
   hostname: mysql-server
   environment:
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   ports:
    - 3306:3306
   security_opt:
    - seccomp:unconfined
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/zabbix/mysql:/var/lib/mysql
   restart: unless-stopped
  
   networks:
    - zbx_net

  zabbix-server-mysql:
   # image: zabbix/zabbix-server-mysql:centos-6.0.8
   image: skypipi/zabbix-server-mysql:centos-6.0.8
   environment:
    - DB_SERVER_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   ports:
    - 10051:10051
   volumes:
    - /data/zabbix/zabbix_log:/var/log/zabbix
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    #- /data/zabbix/zabbix_etc:/etc/zabbix
   depends_on: 
    - mysql-server
   restart: unless-stopped
   
   networks:
    - zbx_net

  zabbix-web-nginx-mysql:
   image: zabbix/zabbix-web-nginx-mysql:centos-6.0.8
   environment: 
    - ZBX_SERVER_HOST=zabbix-server-mysql
    - ZBX_SERVER_PORT=10051
    - DB_SERVER_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   ports:
    - 8080:8080
   volumes:
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    #- /data/zabbix/nginx_etc/conf.d:/etc/nginx/conf.d

   depends_on: 
    - mysql-server
   restart: unless-stopped
   
   networks:
    - zbx_net

networks:
  zbx_net:
