version: "3.9"

services:
  mysql-server:
   image: mysql:8.0.28
   command: 
    --character-set-server=utf8
    --collation-server=utf8_bin
    --default-authentication-plugin=mysql_native_password
   hostname: mysql-server
   environment:
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   volumes:
    - mysql-data:/var/lib/mysql
   restart: unless-stopped

  zabbix-server-mysql-feb:
   image: zabbix/zabbix-server-mysql:centos-6.0.8
   environment:
    - DB_SERVER_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   ports:
    - 10051:10051
   depends_on: 
    - mysql-server
   restart: unless-stopped


  zabbix-web-nginx-mysql-feb:
   image: zabbix/zabbix-web-nginx-mysql:centos-6.0.8
   environment: 
    - ZBX_SERVER_HOST=zabbix-server-mysql
    - ZBX_SERVER_PORT=10051
    - DB_SERVER_HOST=mysql-server
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=zabbix
    - MYSQL_PASSWORD=zabbix_pwd
    - MYSQL_ROOT_PASSWORD=root_pwd
   ports:
    - 8089:8080
   depends_on: 
    - mysql-server
   restart: unless-stopped

volumes:
  mysql-data: {}
